// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpNNxBK_vBHYdKedAguCpv_q_tV3hB7o',
    appId: '1:271805956885:web:e65f2d1faae8a1c32d9f1c',
    messagingSenderId: '271805956885',
    projectId: 'meri-ride-app',
    authDomain: 'meri-ride-app.firebaseapp.com',
    storageBucket: 'meri-ride-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmr3XWCd4lBZ35APOBtoaf68qavxodgqs',
    appId: '1:271805956885:android:7a5fa1e9ae6bc5c12d9f1c',
    messagingSenderId: '271805956885',
    projectId: 'meri-ride-app',
    storageBucket: 'meri-ride-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8eYHr6Sc6ULAacpdROOELtYCHGy9RM9g',
    appId: '1:271805956885:ios:2190db0263e78bd92d9f1c',
    messagingSenderId: '271805956885',
    projectId: 'meri-ride-app',
    storageBucket: 'meri-ride-app.firebasestorage.app',
    iosBundleId: 'com.example.meriRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8eYHr6Sc6ULAacpdROOELtYCHGy9RM9g',
    appId: '1:271805956885:ios:2190db0263e78bd92d9f1c',
    messagingSenderId: '271805956885',
    projectId: 'meri-ride-app',
    storageBucket: 'meri-ride-app.firebasestorage.app',
    iosBundleId: 'com.example.meriRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIpNNxBK_vBHYdKedAguCpv_q_tV3hB7o',
    appId: '1:271805956885:web:dd1100b0dad8e7a72d9f1c',
    messagingSenderId: '271805956885',
    projectId: 'meri-ride-app',
    authDomain: 'meri-ride-app.firebaseapp.com',
    storageBucket: 'meri-ride-app.firebasestorage.app',
  );

}